package view_controller;


import model.Card;//讀取卡牌卡堆
import java.awt.Dimension;//用來對齊視窗
import java.awt.Toolkit;//抽象視窗的工具包
import java.io.*;//提供了所有同步IO的功能
import java.util.concurrent.TimeUnit;//延遲秒數用
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.*;//提供了撥放音樂的功能
import javax.swing.*;//提供了所有SWING的功能

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class ThisIsGameEntrance extends javax.swing.JFrame {

    Clip clip;
    Icon icon ;
    ImageIcon banana,titleicon;
    /**
     * Creates new form GameEntrance
     * @throws java.io.IOException 讀檔案失敗擲出例外
     */
    public ThisIsGameEntrance() throws IOException {
        banana = new ImageIcon("banana.gif");//設置好標題上面圖案
        icon = new ImageIcon("dude1.jpg");//按鈕小圖案
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton(icon);
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton(icon);
        jLabel2 = new javax.swing.JLabel(banana);
        jButton5 = new javax.swing.JButton(icon);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("標楷體", 3, 11)); // NOI18N
        jButton1.setText("進入21點");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("標楷體", 3, 11)); // NOI18N
        jButton2.setText("離開遊戲");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Welcome to StrongGame");
        jLabel1.setToolTipText("");

        jButton3.setFont(new java.awt.Font("標楷體", 3, 11)); // NOI18N
        jButton3.setText("進入比大小");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setMaximumSize(new java.awt.Dimension(500, 226));
        jLabel2.setMinimumSize(new java.awt.Dimension(500, 226));
        jLabel2.setPreferredSize(new java.awt.Dimension(500, 226));

        jButton5.setFont(new java.awt.Font("標楷體", 3, 11)); // NOI18N
        jButton5.setText("進入猜拳");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(70, 70, 70)
                        .addComponent(jButton3)
                        .addGap(71, 71, 71)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(10, 10, 10)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
 *  撥放音樂
 */
    private void enterBgm(){//撥放音樂
        try {
            Clip bgm = AudioSystem.getClip();//設置可以讀音樂的Clip型態
            InputStream is =TwoOne.class.getClassLoader().getResourceAsStream("entergame.wav");//先把音樂讀到 is
            AudioInputStream ais = AudioSystem.getAudioInputStream(new BufferedInputStream(is));//再把他轉到撥放音樂系統裡
            bgm.open(ais);//打開
            bgm.start();//開始
            System.out.println("sucessful");
        } catch (LineUnavailableException | UnsupportedAudioFileException | IOException e) {
            System.out.print("fall");
        }
    }
    /**
     * 撥放音樂
     */
    private void leaveBgm(){//同上
        try {
            Clip bgm = AudioSystem.getClip();
            InputStream is =TwoOne.class.getClassLoader().getResourceAsStream("nigga.wav");
            AudioInputStream ais = AudioSystem.getAudioInputStream(new BufferedInputStream(is));
            bgm.open(ais);
            bgm.start();
            System.out.println("sucessful");
        } catch (LineUnavailableException | UnsupportedAudioFileException | IOException e) {
            System.out.print("fall");
        }
        
    }
    /**
     * 
     * @param evt 按下之後會進入21點 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        enterBgm();
        String[] args = null;
        try {
            TwoOne.start(args);//進入21點遊戲
        } catch (UnsupportedAudioFileException | LineUnavailableException | IOException ex) {
            Logger.getLogger(ThisIsGameEntrance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * 
     * @param evt 按下之後會離開 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        leaveBgm();
        try {
            TimeUnit.SECONDS.sleep(1);//離開前要延遲一秒聽音效
        } catch (InterruptedException ex) {
            Logger.getLogger(ThisIsGameEntrance.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * 
     * @param evt 按下之後會進入比大小 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        enterBgm();
        String[] args = null;
        BigSmall.start(args);//進入比大小
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * 
     * @param evt 按下之後進入猜拳 
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        enterBgm();
        String[] args = null;
        RPS.start(args);//進入猜拳
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThisIsGameEntrance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
         try {
            Clip clip = AudioSystem.getClip();
            InputStream is =TwoOne.class.getClassLoader().getResourceAsStream("bgm1.wav");
            AudioInputStream ais = AudioSystem.getAudioInputStream(new BufferedInputStream(is));
            clip.open(ais);
            clip.start();
            clip.loop(Clip.LOOP_CONTINUOUSLY);
            System.out.println("sucessful");
        } catch (LineUnavailableException | UnsupportedAudioFileException | IOException e) {
            System.out.print("fall");
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            ThisIsGameEntrance Game = null;
            try {
                Game = new ThisIsGameEntrance();
            } catch (IOException ex) {
                Logger.getLogger(ThisIsGameEntrance.class.getName()).log(Level.SEVERE, null, ex);
            }
            Game.setVisible(true);
            Game.setResizable(false);
            //Game.setIconImage(image);
            Game.setTitle("壯祖豪遊戲天堂");
            Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
            int x1 = (int) screensize.getWidth() / 2 - Game.getWidth() / 2;
            int y1 = (int) screensize.getHeight() / 2 - Game.getHeight() / 2;
            Game.setLocation(x1, y1);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
